version: '3.1'
services:
    app:
        image: alfresco/alfresco-content-app
        ports:
            - 3000:80
        depends_on:
            - alfresco
    alfresco:
        image: gui81/alfresco
        ports:
            - 8080:8080
